# 在一切開始前，我們要先建置 pusher 的環境
before_script:
  # 如果 ssh-agent 不存在，更新 apt-get 並且安裝 openssh-client
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  # 當運行 ssh-agent -s 時，會輸出一些 command, 但是他們並還沒有被執行，所以必須使用 eval ，他可以用來執行迭代運算
  - eval $(ssh-agent -s)
  # 將 $SSH_PRIVATE_KEY 加到 ssh agent
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  # 在 docker container 中，建立 .ssh 資料夾
  - mkdir -p /root/.ssh
  # 設定權限
  - chmod 700 /root/.ssh
  - apt-get update
  - apt-get install zip -y
  - echo "$SSH_PRIVATE_KEY"
stages:
  - deploy

project-deploy: 
  stage: deploy
  script:
    - zip  -r ../makeup_service.zip ./
    - scp -o StrictHostKeyChecking=no ../makeup_service.zip root@140.127.74.131:/home/cd
    - ssh root@140.127.74.131 "sudo service apache2 stop && sudo docker kill psgan && sudo docker container rm psgan && sudo rm -r /home/cd/psgan/service && sudo unzip /home/cd/makeup_service.zip -d /home/cd/psgan/service && sudo cp /home/cd/psgan/.env /home/cd/psgan/service/.env && cd /home/cd/psgan && sudo docker build -t psgan . --no-cache && docker run --name=psgan --runtime=nvidia -v /mnt:/mnt -p 9090:80 --restart always -itd psgan && sudo service apache2 start && sudo rm /home/cd/makeup_service.zip"
  only:
    - master