version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    # runtime: nvidia
    volumes:
      - ./service:/app/service
      - ./.env:/app/service/.env
      - ./nginx.conf:/etc/nginx
      - ../photo/Without:/mnt/Without
      - ../photo/Reference:/mnt/Reference
      - ../photo/Synthesize:/mnt/Synthesize
    ports:
      - 9090:80
